CREATE TABLE PRODUCT (
PRODUCT_ID INT PRIMARY KEY,
NAME VARCHAR(50),
RATING INT,
DESCRIPTION VARCHAR(300),
PRICE INT,
STOCK INT,
DISCOUNT INT,
STATUS VARCHAR(10)
);

CREATE TABLE RP_USER (
USER_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
SHIP_ADD VARCHAR(300),
BILL_ADD VARCHAR(300),
PASSWORD VARCHAR(20),
PHONE INT,
EMAIL VARCHAR(30)
);

CREATE TABLE RP_ORDER (
ORDER_ID INT PRIMARY KEY,
USER_ID INT,
PRODUCT_ID INT,
CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES RP_USER(USER_ID),
CONSTRAINT FK_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);